# FREEBASE_DATA = "./data/freebase-head-1000000"
FREEBASE_DATA = "./data/freebase-rdf-latest.gz"
TITLE_FILE = "./files/titles.txt"
TYPE_FILE = "./files/types.txt"
ALT_FILE = "./files/alts.txt"
DIRECTORY = "./files/"
OUTPUT_FILE = "./files/output.txt"
STOP_WORDS = "stop_words.txt"
NON_TYPES = "common_types.txt"
ID = 0
FREQUENCY = 1
